### ISSUE TITLE
More detailed documentation for Windows build

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#111]
Currently, the `rclnodejs` supported Windows 8.1 & 10, however, users may encounter quite annoying issues during building and testing.

* `npm run lint`: this uses `wget` utility, which is not installed by `choco` during in building ros2. 
* Even users install `wget` via `choco install -y wget`, there is still `cpplint` issue when running `npm run lint`:
  ```
  Downloading the cpplint...
  Running the cpplint...


  C:\dev\ros2\wangminggang\rclnodejs\scripts\cpplint.js:35
          throw Error('cpplint failed.');
          ^

  Error: cpplint failed.
      at Error (native)
      at exec (C:\dev\ros2\wangminggang\rclnodejs\scripts\cpplint.js:35:15)
      at ChildProcess.exithandler (child_process.js:205:5)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:920:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
  ```

* rclnodejs depends on thirdparty libraries, so before building rclnodejs, we should run `git submodule update --init --recursive`.

**Comment by minggangw** [comment]
Reopen, as we have more work to do here.

**Comment by minggangw** [comment]
As 49a101e6b560 has been merged, this issue can be closed now.

**Comment by qiuzhong** [comment]
The CI can get through this issue. But it still lacks `wget` dependency installation in the README in case the users tried to build on Windows manually.
