### ISSUE TITLE
One more rclpy API is missing in rclnodejs

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#149]
I just found another `rclpy` API is used in its unit test:
```
rclpy.expand_topic_name.expand_topic_name(topic_name, node_name, node_namespace))
```
It simple wraps the native `rcl_expand_topic_name` API
It's not in the `validator` API family and not listed in #63 
Please also implement this in `rclnodejs`.

**Comment by qiuzhong** [comment]
@minggangw

**Comment by minggangw** [comment]
Got it, will add this one, thanks!

**Comment by qiuzhong** [comment]
Verified. This API works!
