### ISSUE TITLE
[docs]Validator family APIs missing in doc

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#154]
There is no documentation for the APIs of `Validator` class.

**Comment by minggangw** [comment]
It's missed, I will add it to the documentation soon, thanks!

**Comment by qiuzhong** [comment]
@minggangw , not fixed completely. Clicking `validator` module link in the home page of documentation, it said `http://127.0.0.1:8080/module-validator.html`  was not found. (I host the docs via `http-server` command line)

**Comment by minggangw** [comment]
Rechecking...

**Comment by minggangw** [comment]
Oh, stupid I forget to add the newly created html files, let me add them, thanks!

**Comment by qiuzhong** [comment]
Verified. It's complete now. Thanks!
