### ISSUE TITLE
Consider implementing fine-grain destroyXXX() method

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/rclnodejs#184]
These are the unimplemented methods of a `Node`, which provide fine-grain control of the objects inside a node.

```
  destroyPublisher(publisher) {

  }

  destroySubscription(subscription) {

  }

  destroyClient(client) {

  }

  destroyService(service) {

  }

  destroyTimer(timer) {

  }
```

**Comment by minggangw** [comment]
As 514c2a914 has landed, @qiuzhong please add the corresponding unit tests, thanks!

**Comment by qiuzhong** [comment]
Sure.

**Comment by minggangw** [comment]
As the test case has completed since 44e834d4, close this issue now.

**Comment by qiuzhong** [comment]
Verified. All extra destroy methods implemented.

**Comment by minggangw** [comment]
Thanks!
