### ISSUE TITLE
Please include the test folder for the istanbul coverage tool

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#185]
By default, the `test` folder is skipped by `istanbul` tool. Please include this folder explicitly.

**Comment by qiuzhong** [comment]
@minggangw , would you please do me a favor for this? Then I can know the coverage rate of the UT and improve it.

**Comment by minggangw** [comment]
Sure

**Comment by minggangw** [comment]
Please check the coverage result when b453d199778 is landed.

**Comment by qiuzhong** [comment]
Thanks! Close it.
