### ISSUE TITLE
Leverage enhanced RclHandle class to do auto destruction of resource handles

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/rclnodejs#20]
In a dev branch that is not PR-ed yet, the RclHandle class was enhanced to do auto destruction (e.g. calling `rcl_node_fini()`, `rcl_publisher_fini()`, ... and other similar functions along with memory `free()`) of allocated resources.

We should improve our current code logic to adapt this change, leave the resource destruction to RclHandle class dtor (called by V8 GC). In other words, the following lines will not be necessary in the future:
```
rclnodejs.destoryEntity('publisher', publisher.handle, this._handle);
```

**Comment by minggangw** [comment]
Resolve by f614470ea771fa
