### ISSUE TITLE
Possible libuv usage issue: node: ../deps/uv/src/unix/core.c:166: uv_close: Assertion `0' failed.

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/rclnodejs#21]
![image](https://user-images.githubusercontent.com/3302320/27468579-1fc482d6-581d-11e7-81c1-38c35b68e51e.png)

**Comment by kenny-y** [comment]
It happens when running `mocha` on `develop` branch, but not every time...

**Comment by minggangw** [comment]
It seems this never happened again, will reopen if reproduce later.
