### ISSUE TITLE
Ready for Alpha 2 release for rclnodejs

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#215]
After issue #211, #209 are fixed and pr #213 is merged, we can move forward to have our next important release. @kenny-y @qiuzhong @Honry 

Hope we can achieve this by the end of this week :smiley:

**Comment by Honry** [comment]
Cool!

**Comment by minggangw** [comment]
We have released the latest 0.2.0-alpha.2 on [npmjs.com](https://www.npmjs.com/package/rclnodejs), thanks all to make it happen soom :+1:
