### ISSUE TITLE
Cross-language interaction failed

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#222]
Recently when running script:
```
node ./scripts/compile_cpp.js && node ./scripts/run_test.js
```

The appveyor ci fails consistently, please see pr #221, and I noticed that the failed cases are the ones which test the compatibility between `rclnodejs` and `rclpy`/`rclcpp` clients. We verify the messages by reading what has been written to the std out, which may cause some mistake when the console outputs more. e.g. If we enable the debug build, there will be a lot of debug messages which will also influence the test result.

@qiuzhong would you please change the strategy to verify the interaction related functions. Maybe we could create another `publisher/subscription` in `rclpy/rclcpp` to forward what has been `received/published` back to `rclnodejs` instead of reading from console output.

**Comment by minggangw** [comment]
Using our development machine on Linux, all unit tests can pass. But the performance of the machine used by the ci may be not as high as ours, and we have to eliminate the cases which depend on the timing sequence.

**Comment by qiuzhong** [comment]
@minggangw , indeed, by capturing the recipient standard output is not a perfect way. I wonder in 
`rclnodejs publisher -> rclpy/rclcpp subscription` case, how does the subscription send back the message to the rclnodejs publisher nodes? I don't quite understand how to add more `publisher/subscription` nodes in `rclpy/rclcpp` to forward messages?

**Comment by minggangw** [comment]
We can adopt the policy below:

- In `rclnodejs`, create a publisher; In `rclpy`, create a subscription.
- The publisher of `rclnodejs` sends a message to subscription.
- The subscription receives the message from the `rclnodejs` side, then uses another publisher to send back what it just received.
- Again, in `rclnodejs`, create a subscription to receive message from `rclpy` to verify if the message is equal to what it just sent. 

This can improve the ut pass rate on ci, and not a functional requirement.

**Comment by qiuzhong** [comment]
I tried the new strategy to verify the interaction between publisher/subscription and it works. However, there is another issue: the `rclpy` node is quite slow. If run the `rclnodejs` test cases as soon as I launch the `rclpy` node, the `rclpy` node often fails to response as it may not be initialized. So maybe I should still use the timer to send message from `rclnodejs` publisher to `rclpy` subscription and then send it back from `rclpy` publisher to `rclnodejs` subscription and compare the sent and received message.

**Comment by qiuzhong** [comment]
The following unit test files are using the console output and need to use the new strategy for verification:
* test-cross-lang.js
* test-msg-type-cpp-node.js
* test-msg-type-py-node.js
* test-multi-nodes.js

**Comment by minggangw** [comment]
I think we can take advantage of the `stdout` here. When the `rclpy` is ready, then send a specific text, and `rclnodejs` will listen to the output of `stdout` to check the existence of the keyword. Compared with the previous usage of `stdout`, we do not have to find the wording exactly.

**Comment by qiuzhong** [comment]
You mean checking the output (like RegExp) rather than exact word comparison?

**Comment by minggangw** [comment]
Yes, we don't need to do something like `deepEqual`.

**Comment by qiuzhong** [comment]
I update the unit tests to use RegExp for checking the console output. This is for improving the CI pass rate temporarily.

**Comment by minggangw** [comment]
Hi @qiuzhong how about the progress of this issue?

**Comment by qiuzhong** [comment]
I'm afraid it's not as easy as I thought. The publisher/subscription model is just fine. But I got some block for the client/service model even on my Linux system. I'm fixing them.

**Comment by qiuzhong** [comment]
This issue has not been completely fixed.

**Comment by minggangw** [comment]
I notice that there is still frequent failure on mac/linux platforms, so I suggest reverting 5bf3230bcf first and reland when it gets fixed.

**Comment by qiuzhong** [comment]
I'm confused. I cannot reproduced in my branch on the CI right now.

**Comment by qiuzhong** [comment]
#256 all passed to fix this. But let's keep this issue for a while and see if the failure happen again in future.

**Comment by minggangw** [comment]
During the recent commits, all the ci tests passed! It seems cba40f313 has resolved this stubborn problem, excellent job @qiuzhong !
