### ISSUE TITLE
Failed to Assign a New Value to an Array Element

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/rclnodejs#232]
The following test case would fail

``` JavaScript
    const r = Math.round(Math.random() * 100);
    msg1.data[0] = r;
    assert(msg1.data[0] == r);
```

The root cause is that the getter of data property is wrong. We should cache an array in `this` object, clear that cache array when it's necessary, and generate the cache array when requested in `.data` getter when it's empty.

e.g. This the generated code for Int64MultiArray
``` JavaScript
  get data() {
    let values = [];
    this._wrapperFields['data'].data.forEach((wrapper, index) => {
      values.push(wrapper.data);
    });
    return values;
  }
```

Resolution
``` JavaScript
  get data() {
    if (!this.dataArray) {
      this.dataArray = [];
      this._wrapperFields['data'].data.forEach((wrapper, index) => {
        this.dataArray.push(wrapper.data);
      });
    }
    return this.dataArray; // Pass by reference
  }

// TODO: assign undefined to this.dataArray when necessary.
```

TypedArray implementation doesn't have this issue so far.

**Comment by kenny-y** [comment]
@minggangw Would you please look into this? I suppose we should clear `this.dataArray` when doing `.copyRefObject()`, and we should copy `this.dataArray` to `this._wrapperFields['data']` when necessary... is there anything else?

**Comment by minggangw** [comment]
I will take this.
