### ISSUE TITLE
Add script to pack for npmjs.com, using a new README.md

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/rclnodejs#239]
The current `README.md` is for github repo, not 100% suitable for npmjs.com usage.

So I'd like to introduce a new one. When we want to do `npm publish`, we run a script to substitute README.md and then use `npm pack` to generate a tarball and finally publish the tarball instead of the repo dir.

**Comment by minggangw** [comment]
33ce31e33b1 and d26fb4df have landed, so close this issue, thanks!
