### ISSUE TITLE
No implicit signal handler for rclnodejs

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#244]
Well, for `rclcpp` and `rclpy`, if a process is in the event loop, pressing `Ctrl + C` will raise `signal_handler(2)` and `KeyboardInterrupt` and then get the return value `0` and `1` respectively. So this means the `rclcpp` and `rclpy` already handle `SIGINT` by default, users don't need to write explicit handler for cleanup. 

But for a `rclnodejs` process, pressing `Ctrl + C` will simply terminate the process and return `130` code. It seems there is no such cleanup(like `node.destroy()` or `rclnodejs.shutdown()`)

**Comment by minggangw** [comment]
That' right, we must cleanup when the process is terminated.

**Comment by qiuzhong** [comment]
Verified.
