### ISSUE TITLE
Misusage of assert.ok() in UT

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#272]
I found a problem in https://github.com/RobotWebTools/rclnodejs/blob/develop/test/test-compound-msg-type-check.js#L62

```JavaScript
    assert.ok(typeof header.stamp, 'string');
    assert.ok(typeof header.frame_id, 'string');
```

I think we should use `assert.deepStrictEqual()` here, @qiuzhong please double check it, thanks!

**Comment by qiuzhong** [comment]
@minggangw , thanks! You're right, I'll correct it soon.
