### ISSUE TITLE
[Reg] Unit tests got a lot of failures when AMENT_PREFIX_PATH is overrided

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#291]
This issue is triggered from #286 . 

That is when the ROS2 environment variable `AMENT_PREFIX_PATH` is overrided with some other path plus the real `ros2/install` path, the install error of #286 is fixed, but it raises a lot of failures when running the unit tests. Even the unit test suite `test-message-translator` failed.

After replace the `AMENT_PREFIX_PATH` to a single `ros2/install` path, this issue disappears.

**Comment by qiuzhong** [comment]
@minggangw , I think we simply should not override the `AMENT_PREFIX_PATH`.

**Comment by minggangw** [comment]
Thanks, I will check it soon.

**Comment by minggangw** [comment]
Hi @qiuzhong would you please verify this issue under the situation when the `AMENT_PREFIX_PATH` contains more than one path, thanks!

**Comment by qiuzhong** [comment]
@minggangw , with PR293 most failures above are fixed. But there are still some test cases failed due to they will use the `AMENT_PREFIX_PATH` to find the ROS2 applications like  `talker`. However, with multiple paths, the pathname of these applications are invalid.

**Comment by qiuzhong** [comment]
In such case, I don't know which path is the "real" path of ROS2 environment. Basically, this issue will not happen on the CI. I don't think we need to modify the test cases for this specific condition.

**Comment by minggangw** [comment]
I agree, as we will not meet multi-path case on CIs, let's mark this issue as fixed. Thanks!
