### ISSUE TITLE
Thread race condition

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#301]
As `rclnodejs` is the dependency of `ros2-web-bridge`, there is [thread race condition](https://github.com/RobotWebTools/rclnodejs/blob/develop/src/executor.cpp#L102) which may lead the `ros2-web-bridge` server crash. 

There are already some tricky issues in ros2-web-bridge, like [#67](https://github.com/RobotWebTools/ros2-web-bridge/issues/67), [#69](https://github.com/RobotWebTools/ros2-web-bridge/issues/69). And we suspect they're all caused by this thread race condition.

**Comment by minggangw** [comment]
I am going to fix this, thanks!
