### ISSUE TITLE
v0.4.0 release

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#313]
With the landing of [logging utility](https://github.com/RobotWebTools/rclnodejs/issues/281) and [benchmark tests](https://github.com/RobotWebTools/rclnodejs/issues/280), I think it is the proper opportunity to release v0.4.0 which will be the first **stable** release of rclnodejs (we have had 8 alpha&beta releases).

Meanwhile, I hope we can illustrate and compare the performance of rclnodejs with others (rclcpp&rclpy) through the statistics of PnP tests.

@Honry @hanyia @qiuzhong please append issues or patches you want to add into this release.

- [x] Run full testing based on our current [cases](https://github.com/RobotWebTools/rclnodejs/tree/develop/test ) on Linux/Windows/macOS
- [x] Run full testing based on [ros2-web-bridge](https://github.com/RobotWebTools/ros2-web-bridge)
- [x] Check our current online [document](http://robotwebtools.org/rclnodejs/docs/index.html)
- [ ] Add the PnP test result into [README](https://github.com/RobotWebTools/rclnodejs/blob/develop/README.md)
- [x] Issues to be fixed #316 
- [x] Benchmark #361

**Comment by Honry** [comment]
@minggangw, great achievement! I think we should do a full testing before release.

**Comment by qiuzhong** [comment]
And this full testing should also contain the protocol tests in `ros2-web-bridge` as a crash bug was found in `rclnodejs` when running ros2-web-bridge tests.

**Comment by minggangw** [comment]
I will create a check list to track things we want to do in this release. Please edit that list if you have any requirement.

**Comment by minggangw** [comment]
[v0.4.0](https://github.com/RobotWebTools/rclnodejs/releases/tag/0.4.0) has been published, we will add the PnP result later.
