### ISSUE TITLE
Add the actions feature in rclnodejs

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#314]
We want to support and expose the [actionlib](http://wiki.ros.org/actionlib) interfaces by leveraging the [actionlib_nodejs](https://github.com/RethinkRobotics-opensource/actionlib_nodejs), which is an implementation of actionlib on ROS and ROS2. A another issue https://github.com/RethinkRobotics-opensource/actionlib_nodejs/issues/2 is tracking this task on the repo.

**Comment by minggangw** [comment]
The implementation will be submitted to the [actionlib](https://github.com/RobotWebTools/rclnodejs/tree/actionlib) branch.

**Comment by qiuzhong** [comment]
@minggangw , is this feature implemented completely by PR #319 ?

**Comment by minggangw** [comment]
No, only part of it, there will be other patches to integrate the functions.
