### ISSUE TITLE
Add guard condition feature

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#315]
We should implement the guard condition based on [rcl](https://github.com/ros2/rcl/blob/master/rcl/include/rcl/guard_condition.h#L32) library.

**Comment by mattrichard** [comment]
@minggangw If you're not working on this I might take a stab at it. It looks relatively simple to implement, but the actual usage is more difficult to understand since there's very little documentation about guard conditions.

**Comment by minggangw** [comment]
I'm not working on it, please go ahead. I'd like to share some my understandings of this feature:

guard condition acts as a sort of `EventEmitter` in Node.js, offering the event-driven mechanism in ROS2. One difficult point I remember is that we have to find out which guard has been triggered and pass it to the main thread. (In the current design, we don't get the entities that need to be handled)

**Comment by minggangw** [comment]
Hi @mattrichard we have a slack channel at https://rclnodejsdev.slack.com/ created by @wayneparrott (thanks for creating it), you could join in and I think it will facilitate our daily development. I have sent the invitation to @koonpeng already 😄

**Comment by mattrichard** [comment]
@minggangw if you could send an invitation to matthew.w.richard@gmail.com that would be awesome.

**Comment by minggangw** [comment]
> if you could send an invitation to matthew.w.richard@gmail.com that would be awesome.

Done
