### ISSUE TITLE
Test cases for generating .msg from .action files

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#331]
Since the rclnodejs is about to supporting action feature, see #314 and #319, there should be auto test cases to cover this.

**Comment by qiuzhong** [comment]
PR #337 was merged on `actionlib` branch and needs to merge to the master branch

**Comment by minggangw** [comment]
Yes, the `actionlib` is a feature branch and will be merged back to the `develop` when all implementations are ready, thanks!

**Comment by minggangw** [comment]
Close, as already merged with `actionlib` branch
