### ISSUE TITLE
Figure the potential issue behind an endurance test

### ISSUE THREAD

**Issue by kenny-y** [RobotWebTools/rclnodejs#34]
In an endurance test that lasts for days:
 - Node.js client publisher: still working after 16,058,500 messages published (`rcl_init` and `rcl_shutdown` between every 2 messages)
 - Node.js client subscription: stopped working after 1,629,680 messages (got stuck and can't take any new messages)
 - C++ client subscription (`examples_rclcpp_minimal_subscriber_lambda`): stopped working after 6,185,940 messages (got stuck and can't take any new messages)

Note: a new instance of subscription of C++ or Node.js can take new messages from the Node.js publisher.

**Comment by kenny-y** [comment]
CC @minggangw

**Comment by minggangw** [comment]
It sees that with the latest master branch of [ROS2.0](https://github.com/ros2/ros2/blob/master/ros2.repos), the stability is better now and more robust, so close this.
