### ISSUE TITLE
[rosidl_gen]Accept a plain object to be assigned to the property of a message

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#351]
For the current JavaScript messages generated by `rosidl_gen`, if the property is another kind of message, e.g. `std_msgs/Header`

```
builtin_interfaces/Time stamp
string frame_id
```

the `stamp` is the type of `builtin_interfaces/Time`, and you have to assign to it with an object of the exact type. 

``` JavaScript
let header = new Header();
let stamp = new Time({sec: 100, nanosec:100});
header.stamp = stamp;
``` 

We want to implement the code below to simplify it:

``` JavaScript
let header = new Header();
header.stamp = {sec: 100, nanosec:100};
```

**Comment by qiuzhong** [comment]
Tried on `actionlib` branch, the simplified way:
```
let header = new Header();
header.stamp = {sec: 100, nanosec:100};
```
can work well.

**Comment by minggangw** [comment]
Close, as already merged with `actionlib` branch
