### ISSUE TITLE
Use postinstall to generate the JavaScript messages

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#356]
As the rclnodejs will generate the JavaScript messages based on the IDL files (.srv/.msg), the time consumption of first-time start up is usually over several seconds.

We want to move the generation of the messages to the stage of installing to accelerate the start up speed for the first time.

**Comment by qiuzhong** [comment]
@minggangw , does this mean that `rclnodejs.init()` will not generate these message files any more?

**Comment by minggangw** [comment]
During the installation (`npm install`), the message files will be created, and if `rclnodejs.init()` finds that the work has been done, they will not generated again which can accelerate the speed of start up.

@qiuzhong please verify this issue with #357 to check if the needed messages are generated after the execution of `npm install`. Thanks!

**Comment by qiuzhong** [comment]
Sure. I'm testing for it.

**Comment by qiuzhong** [comment]
Just tried #357  and it worked!
