### ISSUE TITLE
 Parameters can be passed through CLI

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#421]

**Comment by suab321321** [comment]
Can you provide me the description for this?

**Comment by minggangw** [comment]
#416 has a brief introduction and you can prioritize them to develop, and take care of the potential dependency between them.

**Comment by wayneparrott** [comment]
I've started working on a parameter server. Will share details soon.

**Comment by minggangw** [comment]
Close due to 800653424f641fbbb831784f1bfb38c6155f2720
