### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#46]
Build rclnodejs on macos platform, and pass the tests.

**Comment by kenny-y** [comment]
Started working on this.

Build is success with minor changes so far.

**Comment by kenny-y** [comment]
#75 can make it build on macOS and run timer example.

The rest features are being worked on...

**Comment by minggangw** [comment]
Move this to M2, as we have limited resources.

**Comment by minggangw** [comment]
Start working on this issue and #72 .
