### ISSUE TITLE
COLCON_PREFIX_PATH vs AMENT_PREFIX_PATH

### ISSUE THREAD

**Issue by robotpilot** [RobotWebTools/rclnodejs#474]
The [binding.gyp](https://github.com/RobotWebTools/rclnodejs/blob/develop/binding.gyp) file uses `COLCON_PREFIX_PATH` instead of `AMENT_PREFIX_PATH`. However, [README.md](https://github.com/RobotWebTools/rclnodejs/blob/develop/README.md)(Build Module section) describes `AMENT_PREFIX_PATH`. Which is the correct explanation?

**Comment by minggangw** [comment]
Oops, this is historical issue caused by the toolchain transition from ament to colcon. Currently, both of the two varieties are supported by ROS 2, but I suggest to use the colcon.

@robotpilot thank for pointing it out, I will unify this information in the README file.

**Comment by robotpilot** [comment]
LGTM!
Thanks, @minggangw :)
