### ISSUE TITLE
Support ROS2 Dashing

### ISSUE THREAD

**Issue by testkit** [RobotWebTools/rclnodejs#493]
ROS2 dashing release is ready (https://discourse.ros.org/t/ros-2-dashing-diademata-released/9365), may I know what's the plan to support this version? Thanks!

**Comment by minggangw** [comment]
Should support soon! :smile:

**Comment by minggangw** [comment]
A new version v0.10.0 has just released, you are welcome to have a try and give your feedback, thanks!
