### ISSUE TITLE
node-gyp --debug rebuild fails

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#556]
While building rclnodejs for debugging I encountered the following error. To replicate run `node-gyp --debug rebuild`. 
```
 CXX(target) Debug/obj.target/rclnodejs/src/addon.o
gyp info spawn args [ 'BUILDTYPE=Debug', '-C', 'build' ]
../src/addon.cpp: In function ‘void InitModule(v8::Local<v8::Object>)’:
../src/addon.cpp:35:26: error: ‘stdout_color_mt’ is not a member of ‘spdlog’
   auto console = spdlog::stdout_color_mt("rclnodejs");
                          ^~~~~~~~~~~~~~~
rclnodejs.target.mk:126: recipe for target 'Debug/obj.target/rclnodejs/src/addon.o' failed
```
Seems addon.cpp is missing
`#include "spdlog/sinks/stdout_color_sinks.h"`

**Comment by minggangw** [comment]
d2724ffdaaf0c01fce6c0601c254aa16355c5fa0 introudced this bug, which upgraded dependency of `spdlog` from https://github.com/gabime/spdlog/tree/4371092309e999052513b109dc68f7a260153681 to https://github.com/gabime/spdlog/tree/aa65dd89053bea0b7e0ffc8d9be4f152d5c01f44, the latest spdlog has move the declaration of `stdout_color_mt` out of `spdlog.h` header. Thanks for finding this problem.
