### ISSUE TITLE
Use js-beautify to format JS code

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#579]
By using [js-beautify](https://www.npmjs.com/package/js-beautify), we can easily format our JS code. e.g.  `npm run format`

**Comment by mattrichard** [comment]
We could take it one further and use [husky](https://github.com/typicode/husky) or [lint-staged](https://github.com/okonet/lint-staged) (or both) to auto-run the formatting when running `git commit`.

You can find an example [here](https://github.com/facebook/create-react-app/blob/2030ee162df0ca8f19efedcf0447e02613e2f53d/package.json#L49).

**Comment by minggangw** [comment]
That's more convenient and I will have a look then, thanks!
