### ISSUE TITLE
Namespce of node/topic

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#58]

**Comment by minggangw** [comment]
@qiuzhong would you help to verify this on `rclnodejs`, you can reference https://github.com/ros2/rclpy/blob/22bc843c40ddb2f0ac79be69693484b18ca2a9b7/rclpy/test/test_node.py#L29 to see the usage, the interface of `rclnodejs` is similar with the one of `rclpy`, thanks!

**Comment by qiuzhong** [comment]
@minggangw , sorry for the reply you late. 

Actually, the `rclnodejs` has already supported the namespace of node/topic. There are some cases in `test-node.js` cover this. However, some APIs like
* `node.get_namespace()`
* `node.get_name()`
in `rclpy` are not available in `rclnodejs`. I believe you'll implement them in M4.

**Comment by minggangw** [comment]
I see, the `node.get_namespace()` and `node.get_name()` are recorded in #63, so I think we can close this one now.

**Comment by qiuzhong** [comment]
Agreed. Please close it.

**Comment by minggangw** [comment]
Thanks, and closing...
