### ISSUE TITLE
how to get multiple topic data at the same time

### ISSUE THREAD

**Issue by EliotCao** [RobotWebTools/rclnodejs#587]
I am new about ros and I want get multiple topic data using Rclnodejs as description in subscription example, is there possibility?
appriciate for you help.

**Comment by wayneparrott** [comment]
I believe what you are seeking is a [ros message_filter](http://wiki.ros.org/message_filters?distro=eloquent) which to my understanding has not yet been implemented by this project.  Until it's implemented a fallback approach would be to implement a simple version that meets your project needs.

**Comment by EliotCao** [comment]
thanks for your reply

**Comment by wayneparrott** [comment]
@EliotCao I've started looking into your question a bit deeper and while message_filters are how you can accomplish this in python or C, there is not yet a primary message_filter-like solution. If I had to solve this problem today I would give RxJS a hard look as it seems like it is made for these type of event and timing based problems. I'll follow up with an example soon if you're still looking at this problem.

**Comment by EliotCao** [comment]
I'm not working on it, but it maybe valuable for others. thanks a lot.
