### ISSUE TITLE
LifecycleNode support in rclnodejs

### ISSUE THREAD

**Issue by mattrichard** [RobotWebTools/rclnodejs#589]
rclnodejs should support lifecycle (a.k.a managed) nodes.

https://github.com/ros2/demos/blob/master/lifecycle/README.rst

**Comment by wayneparrott** [comment]
I reviewed the lifecycle design and the rcl and rclcpp implementations. Implementing a rclnodejs lifecycle node using the rcl lifecycle api looks straight forward. I have an early working version which I need to write tests. Hoping to commit a PR next week for this feature.

**Comment by minggangw** [comment]
Excited to know that, we are closing the gap!

**Comment by minggangw** [comment]
Thanks for @wayneparrott's contributions, we are one step closer to the full-feature client 🚀
