### ISSUE TITLE
Integrate tests with travis-ci

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#59]

**Comment by qiuzhong** [comment]
Why docker build is in the CI configuration file? IMHO, docker build and CI build should be separated as they play different roles. Docker is for shipping application, CI is for checking update.

**Comment by minggangw** [comment]
Because ROS2.0 must be built on Ubuntu16.04(xenial) which travis-ci doesn't support now, we have to leverage the docker.

**Comment by minggangw** [comment]
Since 3e2412aa3c has been merged, mark this task as done.
