### ISSUE TITLE
Differences between this and rosnodejs?

### ISSUE THREAD

**Issue by trusktr** [RobotWebTools/rclnodejs#617]
Just curious, what are the differences between rclnodejs and [rosnodejs](https://github.com/RethinkRobotics-opensource/rosnodejs#readme).

**Comment by minggangw** [comment]
rclnodejs is designed for [ROS2](https://github.com/ros2/ros2), while rosnodejs is for ROS1.

**Comment by trusktr** [comment]
Oh, I see. I'm on ROS 1, and should probably head over to rosnodejs then. I'm new to ROS.  Thanks!
