### ISSUE TITLE
How to destroy Subscription? How to subscribe just for a while?

### ISSUE THREAD

**Issue by zentala** [RobotWebTools/rclnodejs#628]
I would like to get some data from the topic and then close/exit from the subscriber. Is it possible? How?

**Comment by wayneparrott** [comment]
Setup a normal subscription:
```
let subscription = node.createSubscription(...)
```
Then when subscription is no longer needed destroy it:
```
node.destroySubscription(subscription);
```

**Comment by zentala** [comment]
It throws an error: `Callback must be a function. Received undefined`
Indeed `subscription` is an `object`, not a `function`.

**Comment by zentala** [comment]
It's working! Thanks.

**Comment by minggangw** [comment]
Close this issue marked as resolved.
