### ISSUE TITLE
 Some APIs missed in rclnodejs in contrast to rclpy

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#63]
In contrast to [rclpy](https://github.com/ros2/rclpy), some methods are not implemented. So I failed to translate some rcpy test cases that call these methods to rclnodejs. Here is the list of these methods:

| Methods | Used in rclpy tests |
| --- | ---|
| rcl.node getter/setter | [TestNode.test_accessors](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_node.py#L39) |
| rcl.node.handler getter/setter | [TestNode.test_accessors](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_node.py#L39) |
| node.get_namespace() | [TestCreateNode.test_create_node_with_empty_namespace](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_create_node.py#L52) |
| node.get_name() | [TestNode.test_accessors](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_node.py#L40) |
| rcl.spin_once() | [test_timer_zero_callbacks10hertz](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_timer.py#L42) |
| rcl.validate_full_topic_name.validate_full_topic_name() | [TestValidateFullTopicName.test_validate_full_topic_name](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_full_topic_name.py#L32) |
| rcl.topic_or_service_is_hidden.topic_or_service_is_hidden() | [TestTopicOrServiceIsHidden.test_topic_or_service_is_hidden](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_topic_or_service_is_hidden.py#L44) |
| rcl.validate_node_name.validate_node_name() | [TestValidateNodeName.test_validate_node_name](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_node_name.py#L29) |
| rcl.test_validate_topic_name.test_validate_topic_name() | [TestValidateTopicName.test_validate_topic_name](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_topic_name.py#L32) |
| rcl.validate_namespace.validate_namespace() | [TestValidateNamespace.test_validate_namespace](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_namespace.py#L30) |

**Comment by minggangw** [comment]
| Methods | Used in rclpy tests | Used in rclnodejs |
| --- | ---| --- |
| rcl.node getter/setter | [TestNode.test_accessors](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_node.py#L39) | the handle is transparent to developers, and won't change once being assigned, only the getter method will offered. We can do some white-box testing. |
| rcl.node.handler getter/setter | [TestNode.test_accessors](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_node.py#L39) | same with above |
| node.get_namespace() | [TestCreateNode.test_create_node_with_empty_namespace](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_create_node.py#L52) | will add |
| node.get_name() | [TestNode.test_accessors](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_node.py#L40) | will add |
| rcl.spin_once() | [test_timer_zero_callbacks10hertz](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_timer.py#L42) | As we can't control the eventloop in JavaScript, we will drop this |
| rcl.validate_full_topic_name.validate_full_topic_name() | [TestValidateFullTopicName.test_validate_full_topic_name](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_full_topic_name.py#L32) |  will add |
| rcl.topic_or_service_is_hidden.topic_or_service_is_hidden() | [TestTopicOrServiceIsHidden.test_topic_or_service_is_hidden](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_topic_or_service_is_hidden.py#L44) |  will add |
| rcl.validate_node_name.validate_node_name() | [TestValidateNodeName.test_validate_node_name](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_node_name.py#L29) | will add |
| rcl.test_validate_topic_name.test_validate_topic_name() | [TestValidateTopicName.test_validate_topic_name](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_topic_name.py#L32) | will add |
| rcl.validate_namespace.validate_namespace() | [TestValidateNamespace.test_validate_namespace](https://github.com/ros2/rclpy/blob/master/rclpy/test/test_validate_namespace.py#L30) | will add |

**Comment by minggangw** [comment]
Start to work on this issue.

**Comment by qiuzhong** [comment]
Great!

**Comment by minggangw** [comment]
After 4be0126d has been merged, interfaces, excluded `rcl.node getter/setter`, `rcl.node.handler getter/setter` and`rcl.spin_once()`, should be implemented, please @qiuzhong verify it, thanks!

**Comment by qiuzhong** [comment]
@minggangw , I'm writing case to cover them. If I encounter any problems, I will file them.

**Comment by qiuzhong** [comment]
Verified. The missing rclnodejs APIs in the list above are complete and work well except #148.  Test cases are in PR #150

**Comment by minggangw** [comment]
Thanks a lot, I will finish the rest.
