### ISSUE TITLE
How to call a service?

### ISSUE THREAD

**Issue by zentala** [RobotWebTools/rclnodejs#631]
I found how to create a service, but is there any way to call a service?

**Comment by minggangw** [comment]
I suggest you find the examples [here](https://github.com/RobotWebTools/rclnodejs/tree/develop/example) ([client example](https://github.com/RobotWebTools/rclnodejs/blob/develop/example/client-example.js)) and the API [doc](http://robotwebtools.org/rclnodejs/docs/index.html), that's what you need to know how to write a basic ROS2 app by rclnodejs.

**Comment by zentala** [comment]
Thanks and sorry. I didn't notice this example as I have been looking for something with `service` in a name. It may be a good idea to rename this file to `service-client-exmaple.js`.

**Comment by minggangw** [comment]
Thanks for your suggestion, so I think we could close it now. Please feel free to reopen it if you find anything wrong.
