### ISSUE TITLE
generated msg declarations in typescript do not include typed-arrays

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#658]
This is a general question about how typescript declarations for ros msgs represent numeric array properties. For example the `data` property of a ros2 image is defined as  uint8[] in [IDL](https://github.com/ros2/common_interfaces/blob/master/sensor_msgs/msg/Image.msg). Yet the typescript interface generated by rclnodejs (see below) declares the data property as a `number[]`. 
```
export interface Image {
        header: std_msgs.msg.Header;
        height: number;
        width: number;
        encoding: string;
        is_bigendian: number;
        step: number;
        data: number[];
 }
```
Shouldn't `data` in the interface be defined as `number[] | Uint8Array` ?

**Comment by minggangw** [comment]
> Shouldn't data in the interface be defined as number[] | Uint8Array ?

I agree as rclnodejs can adopt both types.

**Comment by wayneparrott** [comment]
@minggangw @mattrichard Please review.

Proposed mapping of [IDL numeric type arrays](https://design.ros2.org/articles/idl_interface_definition.html) to JavaScript typed-array:

| IDL type | JS |
|---------|----|
| int8[]     | Int8Array|
| uint8[]     | Uint8Array|
| int16[]     | Int16Array|
| uint16[]     | Uint16Array|
| int32[]     | Int32Array|
| uint32[]     | Uint32Array|
| int64[] | BigInt64Array |
| uint64[] | BigUint64Array |
| float[] | Float32Array |
| double[] | Float64Array |
| long double[] | ? |  

The plan is to generate optional TS type decls for numeric arrays. 
Example:
```
data: number[] | Uint8Array;
```

**Comment by wayneparrott** [comment]
update: hoping to submit a PR next week (june 24-ish)

**Comment by wayneparrott** [comment]
fixed.
