### ISSUE TITLE
Double init() invoking raises just a warning

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#66]
For `rclnodejs.init()` method, double invoking will raise a warning:
```
init() called
Warning - rclnodejs is already initialized. These arguments will be ignored: []
init() called again
```

My test code (put it in example directory):
```
const rclnodejs = require('../index.js');

rclnodejs.init().then(function() {
    console.log('init() called');
}).then(function() {    
    rclnodejs.init();
    console.log('init() called again');
}).catch(function(err) {
    console.log(err);
});

```

While for `rclnodejs.shutdown()`, double invoking will simply raise an Error.

**Comment by minggangw** [comment]
We'd better uniform these two behaviours (`init` and `shutdown`) to make it consistent, thanks!

**Comment by qiuzhong** [comment]
Verified. The `init` and `shutdown` methods now behave consistently now.
