### ISSUE TITLE
Obscure ros2-rclnodejs version compatibility info leads to installation errors 

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#664]
Proposal: make the ros2-rclnode version compatibility info more pronounced to users on the npm readme.

Recently there have been several installation issues reported because a user installed a version of rclnodejs that is incompatible with their installed version of ros2. The npm readme includes a reference to the version compatibility table but it seems it is easily overlooked.  Because the adherence to the version compatibility requirements is so important for creating a positive 1st impression we should revisit how the info is presented and seek to improve it's visibility.

**Comment by minggangw** [comment]
FYI, the README used by npm locates [here](https://github.com/RobotWebTools/rclnodejs/blob/develop/scripts/npmjs-readme.md), which looks much simpler than the one used by github here. When packaging the rclnodejs, the README will be replaced with the npm copy.

Please feel free to edit any section of README to make it clear and descriptive, thanks!
