### ISSUE TITLE
No TypeScript support for ActionClient destroy() method

### ISSUE THREAD

**Issue by caelinsutch** [RobotWebTools/rclnodejs#687]
If you look at the [API documentation](http://robotwebtools.org/rclnodejs/docs/0.15.0/lib_action_client.js.html), a destroy method is documented. In the [type declaration file](https://github.com/RobotWebTools/rclnodejs/blob/develop/types/action_client.d.ts) no such method is documented. 

I'm opening to submitting a PR for this issue.

**Comment by mattrichard** [comment]
Thanks for reporting this. The type declaration was definitely missing for the `destroy` function. Although, I ended up creating a PR before reading your last line. Feel free to submit PRs for any issues you encounter in the future.

**Comment by caelinsutch** [comment]
When's the estimated release date for v0.16.0?

**Comment by minggangw** [comment]
> When's the estimated release date for v0.16.0?

Currently, we don't have a specific milestone of rclnodejs, but there are some cases that we'll have a feature/bugfix release:

- A new release of [ROS2](https://github.com/ros2/ros2/releases), we always follow the latest ROS2 tightly and verify rclnodejs on it.
- New features are added, e.g. TypeScript support, Action support.
- Critical bugs are fixed, e.g. memory leak...

So, do you want we could publish a bugfix version ASAP to fix this issue?

**Comment by caelinsutch** [comment]
> So, do you want we could publish a bugfix version ASAP to fix this issue?

If you could do a bugfix with this fix and the PR for #688 that would be awesome.

**Comment by minggangw** [comment]
Of course, we could do this. Hopefully, I am going to release 0.15.2 this week, stay tuned.

**Comment by minggangw** [comment]
@caelinsutch please check out v0.15.2 https://www.npmjs.com/package/rclnodejs/v/0.15.2
