### ISSUE TITLE
Problem with space in path

### ISSUE THREAD

**Issue by felixdivo** [RobotWebTools/rclnodejs#711]
It seems like a space in the path causes the Javascript messages file building to crash:

```
> rclnodejs@0.15.1 postinstall /shortened-path-for-privacy/some space/nodejs-project/node_modules/rclnodejs
> node scripts/generate_messages.js

Start JavaScript message generation...
Caught error: Error: python3: can't open file '/shortened-path-for-privacy/some': [Errno 2] No such file or directory
```

Software versions:
- ROS2 Foxy
- Ubuntu 20.04
- Node.js v14.10.1
- rclnodejs 0.15.1

I couldn't yet test whether moving the project solves the issue.

**Comment by minggangw** [comment]
Thanks for submitting this issue, we are going to fix it.

**Comment by felixdivo** [comment]
Thanks. Without the space, I merely get a segfault right after that step. I'll report details once I diagnosed it further.

**Comment by minggangw** [comment]
#699 has fixed the segfault, please try the latest version.

**Comment by felixdivo** [comment]
Thank you, that indeed solved the issue!
