### ISSUE TITLE
Why is there a master branch in this repo?

### ISSUE THREAD

**Issue by felixdivo** [RobotWebTools/rclnodejs#724]
Couldn't it be deleted? It could cause some irritation when cloning and routinely checking out the master branch.

**Comment by minggangw** [comment]
Because we want to follow the rules of RobotWebTools org, `develop`  is used for daily development, while `master` is used for tagging and publishing a version. But, currently, we will create a new branch targeting a ROS2 release accordingly.

**Comment by minggangw** [comment]
Close this issue, please re-open it if you still have questions, thanks!
