### ISSUE TITLE
benchmark code does not build on foxy

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#739]
There are issues building and running the rclcpp and rclpy benchmark code on foxy. 
One issue is the Node#create_publisher() now requires a qos argument.

**Comment by minggangw** [comment]
Yes, the examples haven't been updated for a long time and the interfaces of rclpy/rclcpp have changed.

**Comment by wayneparrott** [comment]
@minggangw I can give this a look next week if you want to assign it to me?

I'm personally interested in seeing the comparative benchmarks between js, c++ and python. Also we might be able to also see how the different DDS middleware performance compares.

**Comment by minggangw** [comment]
Please take this issue, thanks!
