### ISSUE TITLE
Many compiler warnings due to the new Lifecycle API

### ISSUE THREAD

**Issue by felixdivo** [RobotWebTools/rclnodejs#741]
#722 introduced quite a few warnings, see [this recent build from `master`](https://travis-ci.org/github/RobotWebTools/rclnodejs/builds/745789933#L24954).

They all seem to be quire easy to fix though (mainly `warning: variable ‘currentContent’ set but not used`).

**Comment by wayneparrott** [comment]
@felixdivo Thx. 
My BAD! I've gotten too used to seeing compiler warnings with `node-gyp build`. 
I'll submit a fix PR asap.
