### ISSUE TITLE
[docs]The constructors should not be exposed to users

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#81]
Currently the constructors of `Client/Entity/Node/Publisher/QoS/Service/Subscription/Timer` classes are presented in the docs. However, they cannot be referred by users outside. They can only referred after `require('./lib/XXX.js');` inside rclnodejs. 

Meanwhile, they're not supposed to be exposed to users. So they should be removed from the documentation.

**Comment by minggangw** [comment]
I'm going to remove these useless comments, thanks!

**Comment by qiuzhong** [comment]
Verified. The constructors in the docs are removed now.
