### ISSUE TITLE
Using galactic-geochelone binary packages for CI configuration on galactic-geochelone branch

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#830]
We should use the galactic-geochelone binary packages to verify on CIs instead of the latest binary, please see below:

https://github.com/RobotWebTools/rclnodejs/blob/cbfadd98ce877a16de03b560e24181f10a07f97d/appveyor.yml#L35-L36

https://github.com/RobotWebTools/rclnodejs/blob/cbfadd98ce877a16de03b560e24181f10a07f97d/Dockerfile#L35-L36

https://github.com/RobotWebTools/rclnodejs/blob/cbfadd98ce877a16de03b560e24181f10a07f97d/.circleci/config.yml#L50-L51

**Comment by wayneparrott** [comment]
@minggangw Is this what you are referring to by binary package?
```sh
# ros linux installation
sudo apt install ros-galactic-desktop
```

**Comment by minggangw** [comment]
As the daily build (or rolling) ROS2 binary may break the compiling on CIs due to the interface changes of rcl, we'd better use the stable release for its branch accordingly, e.g., [galactic-geochelone](https://github.com/RobotWebTools/rclnodejs/tree/galactic-geochelone) uses the galactic binary package, and the develop branch will always use the daily release build to track the latest changes.

So, I suggest using the package downloaded from the [Github release channel](https://github.com/ros2/ros2/releases), because I noticed that our test needs [test_interface_files](https://github.com/ros2/test_interface_files) package which doesn't exist when installing through `sudo apt install ros-galactic-desktop`, you can double-check whether it's still right.

The current change was introduced by https://github.com/RobotWebTools/rclnodejs/commit/12cd761277ba1affdcc32900a4aab3a3e81fad25, so we can change it back.
![image](https://user-images.githubusercontent.com/6469275/148887605-fb25744a-d30f-4bc5-806f-4194670cc2cc.png)

**Comment by wayneparrott** [comment]
@minggangw apologies as I goofed up the ci ros distro access. Will fix asap.
Reverting the galactic branch ci changes will still leave osx on the "rolling" distro as there are no official osx binaries beyond "foxy". As of the "galactic" release osx was downgraded to a [Tier 3 platform](https://www.ros.org/reps/rep-2000.html#galactic-geochelone-may-2021-november-2022).

**Comment by minggangw** [comment]
> Reverting the galactic branch ci changes will still leave osx on the "rolling" distro as there are no official osx binaries beyond "foxy". As of the "galactic" release osx was downgraded to a Tier 3 platform.

Yeah, I think we have to drop the macOS platform, please #760

**Comment by wayneparrott** [comment]
> Yeah, I think we have to drop the macOS platform, please #760

@minggangw  Agree. Is the process for dropping osx as simple as removing the circleci workflow on the `develop` and `galactic` branches and updating docs?

**Comment by minggangw** [comment]
Yeah, removing the configuration file (config.yml)  and updating the table (README) below is enough
![image](https://user-images.githubusercontent.com/6469275/149177112-e255f0ed-de20-4dc4-ba10-9fb28fa129f7.png)

and we can remove the row for `master` branch status from the table also. Maybe we can remove the table completely and append the two badges (for Windows & Linux) after the other badges?
![image](https://user-images.githubusercontent.com/6469275/149178782-3bbe91fc-b385-4849-bed9-213f14717d1d.png)

**Comment by wayneparrott** [comment]
@minggangw 
1) should we restrict installation of rclnodejs to macOs? 
e.g., add an `os` section to package.json
```
{
  "os": [
    "win32",
    "linux"
  ]
}
```
Alternatively, we could not restrict installation to macOs and instead provide a notice in the readme and npmjs-readme that macOs is not support; install at your own risk?

2) I tweaked the README to get this look in my dev env. The preview of the build-status table in vscode is omitting the borders.
![image](https://user-images.githubusercontent.com/5588978/149205795-63bc7367-33de-4cbd-9605-4bfdfd8a8130.png)
Thoughts? If you like this or want a different layout please advise. Note: the dependencies service at david-dm.org has been offline for a while so I commented out the dependencies status label.

**Comment by minggangw** [comment]
> should we restrict installation of rclnodejs to macOs?

I prefer not to restrict the installation on macOS, because I suppose users should be aware of the fact that there are no official ROS2 releases on macOS. Adding a notice in readme is fine.

> I tweaked the README to get this look in my dev env. The preview of the build-status table in vscode is omitting the borders.

Looks good :) thanks for cleaning it up!

**Comment by minggangw** [comment]
I think we can close this as #832 was merged.
