### ISSUE TITLE
Replace appveyor with Github action/workflow for Windows builds

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#854]
The project recently switch to using Github Actions for Linux builds. This PR proposes to replace the Appveyor CI with Github Actions similar to the Linux build model.

See related issues: #841, #834

**Comment by wayneparrott** [comment]
Currently blocked by bug https://github.com/ros-tooling/setup-ros/issues/491

**Comment by wayneparrott** [comment]
[setup-ros v0.3.4](https://github.com/marketplace/actions/setup-ros-environment) has been released. We should be able to resume work on this. I'm hoping that #856 will reduce many of the past challenges with windows ci.

**Comment by minggangw** [comment]
Good news! Thanks for keeping looking at this issue.

**Comment by minggangw** [comment]
I have stopped the [appveyor](https://ci.appveyor.com/project/minggangw/rclnodejs) for rclnodejs, as it's always failing :(

**Comment by minggangw** [comment]
I think we can mark this as resolved, thanks!
