### ISSUE TITLE
Cleanup the CI badges in README

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#861]
As we have migrated to actions, we are going to remove the original badges for CIs and replace with the action's.

**Comment by minggangw** [comment]
It seems that we have many badges :)
![image](https://user-images.githubusercontent.com/6469275/174123355-29e0c904-85f4-40ad-b7cd-0848b4d78eda.png)

**Comment by minggangw** [comment]
@wayneparrott I remember you have already had a draft for this, would you please update README when you have time, thanks!

**Comment by wayneparrott** [comment]
@minggangw I was just thinking of the need to update our README with the new CI status when I saw this. Will give it a look asap.
