### ISSUE TITLE
QoS members are undefined in constructor

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#87]
In the class `QoS` constructor, the members are initialized as `undefined` like this:
```
class QoS {
  constructor() {
    this._history = undefined;
    this._depth = undefined;
    this._reliability = undefined;
    this._durability = undefined;
    this._avoidRosNameSpaceConventions = undefined;
  }
...
```

IMHO, this is not a good initialization. After you new a QoS object, call the getter of any property you will get an `undefined` type.
However, each getter has a special type for the returned value in the docs.
I would suggest to initialize them as all `false` evaluation values, that is:
* For boolean getter, initialize it as `false`
* For string getter, initialize it as `''`
* For number getter, initialize it as `0`
* For object getter, initialize it as `null`

**Comment by minggangw** [comment]
Good suggestion, I am gonna take this, thanks!

**Comment by qiuzhong** [comment]
Verified. The QoS object properties are initialized in a good way and not undefined now.
