### ISSUE TITLE
QoS setter should check the parameter type

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#88]
Currently, the QoS class setter is simply implemented by assigning the parameter to the inside property:
```
  set history(history) {
    this._history = history;
  }
```

It's better if we do more work on this, like parameter type checking.

**Comment by minggangw** [comment]
Good suggestion, I am gonna take this, thanks!

**Comment by qiuzhong** [comment]
Verified. All the parameters are type-checked before assignment in the QoS setter.
