### ISSUE TITLE
Support Node 18

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#882]
package.json includes this node version constraint:

```javascript
  "engines": {
    "node": ">= 10.23.1 <18.0.0"
  }
```
I ran a quick test with node 18. The rclnodejs test suite passes with node v18.12.1 (LTS) on ROS humble and galactic distros.

@minggangw  Thoughts on expanding support to Node 18?

**Comment by minggangw** [comment]
Agree, we can include the nodejs 18 now, please go ahead to change it, thanks!

**Comment by minggangw** [comment]
Close it due to #884
