### ISSUE TITLE
message generation fails on Rolling due to unsupported *.idl files in ros2bag pkg

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#890]
The Rolling distro for windows includes the rosbag2_storage_mcap_testdata pkg. In this package there is a the  ComplexMsgDependsOnIdl.msg which includes BasicIdl.idl. The rclnodejs message generator only parses *.msg and *.srv files at this time. Thus the message generator fails with an error. Note that message generation is part of the npm install process for rclnodejs. Thus rclnodejs 0.21.4 can not be used with the Rolling distro on Windows at this time.

**Comment by wayneparrott** [comment]
A quick solution is to introduce a mechanism for filtering packages and messages that should not be generated. The `run_test.js` script uses a blocklist.json file to filter test files by OS. I propose we introduce a similar feature for specifying packages and messages to be filtered from the message generation process. Thoughts?

example filter spec:
```
interface MsgGenFilter {
  pkg: Regexp;
  os?: Regexp;
  message?: Regexp;
}
```
Thoughts?

**Comment by minggangw** [comment]
Related issue #764
