### ISSUE TITLE
possible bug when processing raw subscription message?

### ISSUE THREAD

**Issue by wayneparrott** [RobotWebTools/rclnodejs#911]
@minggangw 
In `node.js#execute()` should the following highlighted line be `continue` rather than `return`?

![image](https://user-images.githubusercontent.com/5588978/230959552-72d1522e-c965-494f-8eae-6ce1a6c78974.png)

https://github.com/RobotWebTools/rclnodejs/blame/369e765f38fd0560876bc36e5dc5d85a2ac16171/lib/node.js#L188

**Comment by minggangw** [comment]
@wayneparrott good catching! it should use `continue`, otherwise, other subscriptions will not receive any response which is not raw messge.
