### ISSUE TITLE
Online version of webdocs is not working

### ISSUE THREAD

**Issue by judahtanninen** [RobotWebTools/rclnodejs#917]
The url given for the online version of the JSDocs gives a "We can’t connect to the server at robotwebtools.org" error.

Not sure if there is a new location for the docs or not, just figured I should let y'all know.

Url for docs: http://robotwebtools.org/rclnodejs/docs/index.html

**Comment by wayneparrott** [comment]
@judahtanninen thx for the reminder for this root issue https://github.com/RobotWebTools/robotwebtools.github.io/issues/82

We will work up an alternative, e.g., github pages or similar solution if the robotwebtools domain is not back online soon.

**Comment by minggangw** [comment]
@judahtanninen the doc has been fixed, please try with https://robotwebtools.github.io/rclnodejs/docs/index.html. Close this issue now.
