### ISSUE TITLE
Wrong topic type for /clock

### ISSUE THREAD

**Issue by AntoninRousset** [RobotWebTools/rclnodejs#927]
**Description**
According to the [ROS documentation](http://wiki.ros.org/Clock), clock messages have type [rosgraph_msgs/Clock](http://docs.ros.org/en/api/rosgraph_msgs/html/msg/Clock.html), but rclnodejs [uses builtin_interfaces/msg/Time](https://github.com/RobotWebTools/rclnodejs/blob/70811708796855393ae3da4c51a7dd19829d5216/lib/time_source.js#L188C10-L188C37).

- Library Version: 0.22.2
- ROS Version: Humble
- Platform / OS: Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Steps To Reproduce**
```sh
node <your_rclnodejs_node>.js --ros-args -p use_sim_time:=true
```

**Expected Behavior**
Subscibe to `/clock` with type `rosgraph_msgs/msg/Clock`.

**Actual Behavior**
Subscribe to  `/clock` with type `builtin_interfaces/msg/Time`.

**Comment by minggangw** [comment]
@AntoninRousset [v0.22.3](https://github.com/RobotWebTools/rclnodejs/releases/tag/0.22.3) rolls out with your patch, thanks for fixing this issue, close it now.
