### ISSUE TITLE
Update README for Jazzy release

### ISSUE THREAD

**Issue by minggangw** [RobotWebTools/rclnodejs#973]

**Comment by IoTDan** [comment]
Hello @minggangw ! i see a lot of activity for a Jazzy release. Thank you for this. I wanted to know if you have a general ETA for this? I realize it is best effort. Just looking to see scale of time - days, weeks, months. thank you!

**Comment by minggangw** [comment]
Hi @IoTDan the latest release v0.27.0 has supported Jazzy https://github.com/RobotWebTools/rclnodejs/releases/tag/0.27.0, please have a try. I'm going to complete this task as it's done, thanks!

**Comment by IoTDan** [comment]
Thank you!!! We tried this before last week, so perfect timing!! We will try this again with the v0.27 release.

Thanks,
Dan

**Comment by minggangw** [comment]
Your feedback is welcome!
