### ISSUE TITLE
Link Updates in README

### ISSUE THREAD

**Issue by CursedRock17** [RobotWebTools/rclnodejs#977]
**Description**

Multiple links in this repository's README go to the index.ros.org site instead of docs.ros.org. For instance [this link](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html#source-the-setup-files) can be issued for the configuration of the ROS environment. This is highlighted in [this issue](https://github.com/ros-infrastructure/rosindex/issues/398), though there are a couple of dead links littered throughout. I personally don't have the bandwidth for this issue, but this isn't too hard of an issue to fix.

**Comment by minggangw** [comment]
@CursedRock17 thanks for your feedback, the links in README have been corrected.
