### ISSUE TITLE
Require message type before rclnodejs initialization

### ISSUE THREAD

**Issue by qiuzhong** [RobotWebTools/rclnodejs#98]
In the example of [publisher-message-example.js](https://github.com/RobotWebTools/rclnodejs/blob/develop/example/publisher-message-example.js#L18) and [subscription-message-example.js](https://github.com/RobotWebTools/rclnodejs/blob/develop/example/subscription-message-example.js#L18), the message type classes are required before `rclnodejs` initialization. This may cause failure of requiring them.

**Comment by qiuzhong** [comment]
@minggangw

**Comment by qiuzhong** [comment]
Meanwhile, I'll update PR#96

**Comment by minggangw** [comment]
Thanks for finding this problem, I will fix this in the two examples, thanks!
