### ISSUE TITLE
Broken ROS 2 Documentation Links

### ISSUE THREAD

**Issue by CursedRock17** [RobotWebTools/rclnodejs#981]
Around the documentation in this package, there are various ROS 2 documentation links that are broken, mainly in part due to using index.ros.org opposed to docs.ros.org (where documentation is hosted for each ROS package). [A search](https://github.com/search?q=repo%3ARobotWebTools%2Frclnodejs%20index.ros.org&type=code).

For instance: 

> https://index.ros.org/doc/ros2/Installation/Linux-Development-Setup/.

should instead be:
> https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html

I currently don't have the bandwidth to solve this, but it's a simple solution, perhaps great for new contributors.

**Comment by minggangw** [comment]
@CursedRock17 thanks for your feedback, the links have been updated by https://github.com/RobotWebTools/rclnodejs/pull/982
